name: CI Lint

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2

      - name: Setup Node.js
        uses: actions/setup-node@1e31de5234b9f8995739874a8ce0492dc87873e2
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: make lint
